### ISSUE TITLE
500 Server Error when adding a badly-formed secondary email

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2101]
(I noticed tracebacks related to this in the auth-server app logs while digging in to something else.)

If you try to add a secondary email that's has an invalid domain component, such as "test@example.42", then you get a 500 response and an "unexpected error" UI:

<img width="415" alt="capture" src="https://user-images.githubusercontent.com/34695/30193044-5937343e-948e-11e7-8384-3fbc7460fcb0.PNG">

This appears to be postfix failing to send the email, and us not catching the error.  Here's the traceback from kibana:

<img width="1002" alt="capture" src="https://user-images.githubusercontent.com/34695/30193085-9c6ee008-948e-11e7-98f9-d2bab3d85e60.PNG">

Should we be rejecting these undeliverable emails during validation?  Should we be catching and handling the error from postfix?  Should we remove the address from the account if we fail to send the verification email?  @jrgm @vbudhram I'd be interested in your thoughts here.

**Comment by vladikoff** [comment]
cc @vbudhram to check, but should be fixed

**Comment by vbudhram** [comment]
@rfk Could not reproduce this locally with mem and mysql db and using train-95 branch. However, I am able to see this on production and stage environments. Moving this to blocked until I can retest on stage with train-96.

> Should we be rejecting these undeliverable emails during validation? Should we be catching and handling the error from postfix? Should we remove the address from the account if we fail to send the verification email?

My vote would be not delete the email, but catch and handle the error. If the user refreshes page (not intuitive by any means) then the email would show up and they would have an option to resend the verification. However, I don't have a strong opinion on it either way. Once train-96 is live, I would be curious how often this type of error shows up.

**Comment by rfk** [comment]
> Could not reproduce this locally with mem and mysql db and using train-95 branch.
> However, I am able to see this on production and stage environments

IIUC, the error will only be triggered when you've got postfix rejecting the attempt to send the email, which would explain why it doesn't trigger in a local setup.

> If the user refreshes page then the email would show up and they would have an option
> to resend the verification

I don't believe they will ever be able to successfully send to such an address; however, leaving it in the list and showing a clean error message about 'failed to send' and giving them the ability to manually clean it up seems OK to me.

**Comment by vbudhram** [comment]
Still getting a couple occurrences of this, https://sentry.prod.mozaws.net/operations/auth-prod/issues/652296/.

> I don't believe they will ever be able to successfully send to such an address; 

Reconsidering, I think it would be ok to error cleanly and delete the email. PR inbound.
